#!/usr/bin/env bash

paths=$1

for gitpath in $paths;
do
    path=$(printf "$gitpath" | awk -F ':' '{ print $1 }')
    REMOTE=$(printf "$gitpath" | awk -F ':' '{ print $2 }')
    HOST=$(printf "$gitpath" | awk -F ':' '{ print $3 }')
    REPO=$(printf "$gitpath" | awk -F ':' '{ print $4 }')

    REMOTE_REPO="$HOST:$REPO"

    echo "checking repo at '$path'"
    mkdir -p $path
    cd $path
    CURRREPO=$(git remote -v | grep "$REMOTE" | grep "fetch" | awk '{ print $2 }')

    echo $CURRREPO ' ' $REMOTE_REPO

    if [[ "$CURRREPO" == "$REMOTE_REPO" ]]
    then
        echo 'repo exists'
    else
        echo 'repo does not exist at path, cloning...'
        git clone $REMOTE_REPO .
        echo 'cloned...'
    fi
done